export const PERMISSIONS = {
  USER_CREATE: "user.create",
  USER_READ: "user.read",
  USER_UPDATE: "user.update",
  USER_DELETE: "user.delete",
  USER_TOGGLE_ACTIVE: "user.toggleActive",
  EVENT_CREATE: "event.create",
  EVENT_READ: "event.read",
  EVENT_UPDATE: "event.update",
  EVENT_DELETE: "event.delete",
  COMMENT_CREATE: "comment.create",
  COMMENT_READ: "comment.read",
  COMMENT_UPDATE_OWN: "comment.update.own",
  COMMENT_DELETE_OWN: "comment.delete.own",
  COMMENT_DELETE_ANY: "comment.delete.any",
  GROUP_CREATE: "group.create",
  GROUP_READ: "group.read",
  GROUP_UPDATE: "group.update",
  GROUP_DELETE: "group.delete",
  ROLE_READ: "role.read",
  ROLE_CREATE: "role.create",
  ROLE_UPDATE: "role.update",
  ROLE_DELETE: "role.delete",
} as const;
